name             'Task6'
maintainer       'Dmytro'
maintainer_email 'dfad1ripe@gmail.com'
license          'none'
description      'IIS/fetch/restart'
long_description 'Installs/Configures IIS, schedules fetch/restart'
version          '0.1.0'
issues_url       'http://bash.im/'
source_url       'https://github.com/dfad1ripe/df_devops_task6'
depends          'windows'
